/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_JNISimpleDemo */

#ifndef _Included_org_example_JNISimpleDemo
#define _Included_org_example_JNISimpleDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_JNISimpleDemo
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_JNISimpleDemo_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
