/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_JNIAdvancedDemo */

#ifndef _Included_org_example_JNIAdvancedDemo
#define _Included_org_example_JNIAdvancedDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_JNIAdvancedDemo
 * Method:    nativeAdd
 * Signature: (Lorg/example/NameReceiver;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_example_JNIAdvancedDemo_nativeAdd
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
